ProjectD-v0:
  n_timesteps: !!float 1e7
  policy: 'MlpPolicy'
  policy_kwargs: "dict(net_arch=[128, 128])"
  learning_rate: !!float 7.3e-4
  learning_starts: 666
  buffer_size: 300000
  batch_size: 256
  ent_coef: 'auto'
  gamma: 0.98
  tau: 0.02
  #train_freq: 1
  train_freq: [1, "episode"]
  #gradient_steps: 1
  gradient_steps: 64
  use_sde: True
  use_sde_at_warmup: True
  sde_sample_freq: 64
  #normalize: True
  normalize: "{'norm_obs': True, 'norm_reward': False}"
  